# per-machines overrides: put tweaks in ~/.config/alacritty/local.toml

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 86
dimensions.lines = 28
padding.x = 10
padding.y = 10
opacity = 1.0

[font]
size = 12.0

[font.normal]
family = "Ioskeley Mono"
style = "Regular"

[font.bold]
family = "Ioskeley Mono"
style = "Bold"

[font.italic]
family = "Ioskeley Mono"
style = "Italic"

[font.bold_italic]
family = "Ioskeley Mono"
style = "Bold Italic"

[cursor]
style.shape = "Beam"
style.blinking = "On"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
